### ISSUE TITLE
Improve selected item appearence in the left menu

### ISSUE THREAD

**Issue by Popov72** [BabylonJS/Documentation#13]
Unity is making it bold + underline when selected, and underline when hover, for eg.

**Comment by RaananW** [comment]
@PatrickRyanMS - want to weigh in on this one?

**Comment by PatrickRyanMS** [comment]
I went back to the original design and made a couple of tweaks to make your position stand out more. Not a fan of the underline because it will clip descenders on the type, and an underline commonly means "this is a link" when the whole ToC are links. The tweaks come in two parts to emphasize where you are. 

- Make the type for the ToC default to color #6E6259 in Acumin Pro Regular (400)
- Make the hover color for the type #272320 and retain the Regular (400) weight
- Make the active state (where you are currently in the bread crumb trail) color #272320 and in a Black (800) weight
- Leave all parents of your current location in their original color (#6E6259) and weight (400) so that the only highlighted section is the page you are currently viewing in the main panel

This should improve the contrast of the location in the ToC and make it easier for you to know where you are.

![image](https://user-images.githubusercontent.com/31326855/98850718-08bfea00-240a-11eb-8ea6-18ce7943b207.png)
