### ISSUE TITLE
Please delete and re-create this repository

### ISSUE THREAD

**Issue by DelvarWorld** [BabylonJS/Documentation#147]
I was surprised when I cloned this repo to find it was about 1gig of data. That doesn't make any sense for a documentation site.

It appears you're committing dozens of multi MB built files https://github.com/BabylonJS/Documentation/tree/master/data which looks like some sort of search indexed data?

It's a fundamental git (and general VCS) principle not to commit built files. It appears to be the case here that you're committing huge built files to this repository. There are two ways to decrease the size of this repository:

 - Use `git filter-branch` to destructively remove every built file from every commit. This is destructive to the commit history and will invalidate all hashes, and will require a significant community announcement and preparation. Any unmerged branches / open PRs will need to be recreated by hand.

- Or, delete this repository and create a clean one with no built files in it. Github currently supports [repository redirects](https://github.com/blog/1508-repository-redirects-are-here) so this would be simple, and there's only one open PR.

Please correct me if I'm wrong. It looks like you're committing built files to a git repo, which is fundamentally wrong in VCS strategy. If there's some obvious reason you do this, incredibly bloating the repo size (1gig for a text repo!!), permanently ruining commit history (huge diffs) and permanently ruining repo searchability, please let me know.

**Comment by Temechon** [comment]
Hello DelvarWorld, 
Thank you for your pull request, and thank you for your feedback.
Indeed, the repository contains a lot of compiled files (*data* contains all search indexes in order to allow users to search within the website).You are totally right about your comment saying these built files should not be present in the repo.

The only reason that these files are in the repo is the documentation is build over a [Github to Azure](https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/), which allow us to have a very up to date documentation at each commit.
Therefore, we cannot simply delete these files as you would like to.
Please tell me if this answer to your questions, and don't hesitate to come back to me if you have a workaround.

Cheers, 

Julian

**Comment by DelvarWorld** [comment]
There are numerous ways to fix this. I haven't used that proprietary software but it's as simple as either building the files on your local machine then pushing them, or building a tarball and pushing it (like AWS), or building the files on the remote machine (like basic Heroku). I imagine Azure has a build step / pipeline. A repository is for **source** code, independent of what type of project it is. It is **not** for deployed compiled code. Please re-open this ticket until the build process has been updated and built files have been scrubbed from the history.
