### ISSUE TITLE
Explain `engine` variable

### ISSUE THREAD

**Issue by LukeTOBrien** [BabylonJS/Documentation#165]
Hello there,

Your documentation is really wonderful, the best I've seen - Even better than MSDN

In your [Chapter 1](https://doc.babylonjs.com/start/chap1/first_scene#say-hello-to-your-first-world) you talk about the scene and you have the following code:

```ts
const scene = new BABYLON.Scene(engine);
```

You don't seem to explain what the `engine` variable is, unless I missed it, I noticed from a later code snippet that it is a `BABYLON.Engine` but I think you need to explain that in Chapther 1

**Comment by thomlucc** [comment]
Really great suggestion! @PirateJC can we add something here?

**Comment by rdw-software** [comment]
I concur, I didn't understand what an "engine" is supposed to be or why I as a beginner should care about it either back when I started using BabylonJS.

IMHO, the following questions should be answered:

* What is the ``Engine``?
* Why is it needed?
* What else can I do with it (link to API docs/further reading, too much information otherwise)?

**Comment by PirateJC** [comment]
Awesome suggestions everyone! Sorry for the delay in getting to this.

I've added a description of why the engine variable is needed in the scene constructor:

https://github.com/BabylonJS/Documentation/pull/404
