### ISSUE TITLE
Getting started - "Babylon viewer" page detracts from flow for beginners

### ISSUE THREAD

**Issue by brian-hay** [BabylonJS/Documentation#392]
This is more of an observation and I just wanted to open it up for discussion. I was re-reading the "Getting Started" docs, trying to look at them from a beginner perspective.

The second page https://doc.babylonjs.com/start/chap1/first_viewer I feel is necessary yes, but possibly not the right place for it, as using the viewer to display 3D models is quite different to creating your first basic scene using code, which is how the section starts. It could be quite jarring/confusing for beginners.

**Comment by sebavan** [comment]
This is a pretty good remark !!! Let s see what @PirateJC and @RaananW think about it ?

**Comment by PirateJC** [comment]
@brian-hay thanks for sharing your perspective. I tend to agree that it might be a little out of the "flow"for a beginner. The hard part here is that each of us brings different understanding and knowledge to what we think about when we say "beginner." 

Let me think about this for a little bit and if moving it do a different place is the right decision here. 

Also adding @BabylonJSGuide to weigh in as well since he wrote the Getting Started Section.

**Comment by RaananW** [comment]
@PirateJC - reminding you that this isue is open (to be considered when restructuring the docs)

**Comment by PirateJC** [comment]
Hey @brian-hay, we've recently released a new organization of the docs, where the "Getting Started" section is now actually under a new uber heading called "Features." I think your comment is still potentially valid, that some folks might not consider the viewer to be a beginner topic, but the more I think about it, the more I think we should leave it as is for now...especially considering the new organization. Thanks so much for raising the issue though! We'll revisit it again if it feels like a persistent problem for folks.
