### ISSUE TITLE
Link to Going the Distance with Babylon.js book is broken

### ISSUE THREAD

**Issue by sheepsteak** [BabylonJS/Documentation#867]
[content/guidedLearning/journeyBeyond.md](https://github.com/BabylonJS/Documentation/blob/master/content/guidedLearning/journeyBeyond.md?plain=1#L13)

The https://packt.link/josh link seems to be a 404 rather than go to https://www.packtpub.com/product/going-the-distance-with-babylonjs/9781801076586 (presumably?)

cc @jelster (found you from book repo 😄)

**Comment by jelster** [comment]
hi @sheepsteak thanks for pointing this out! The correct link should be https://packt.link/Josh -- it is tragically a case-sensitive link that my publisher provided me. @PirateJC -- would you prefer a PR for this or is this something you'd prefer to fix yourself?
_ed: it's a bit weird that the link doesn't point to the packtpub site and instead goes straight to amazon, but 🤷 I'll email the publisher and see if that's intentional or not_

**Comment by RaananW** [comment]
@jelster - please submit a PR with the right link, i'll merge it asap :-)

**Comment by jelster** [comment]
Thanks, [done](https://github.com/BabylonJS/Documentation/pull/869)!
